name: Build images and deploy

on:
  push:
    branches:
      - main

env:
  REGISTRY: registry.kalek.dev
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          target: final
          tags: ${{ env.REGISTRY }}/${{ github.event.repository.name }}:latest
      - name: Redeploy stack
        run: |
          curl --request POST \
            --url https://stacker.kalek.dev/update/${{ secrets.STACKER_SECRET }} \
            --header 'Content-Type: application/json' \
            --data '{"stack": "main", "composeFile": "docker-compose.yml","gitPull": false}'